---
  el:
    hosts:
      centos:
        ansible_connection: docker
  deb:
    hosts:
      debian:
        ansible_connection: docker
  localhost:
    hosts:
      local:
        ansible_connection: local
  fed:
    hosts:
      fedora:
        ansible_connection: docker
